build_from:
  aarch64: "f0rc3/barcodebuddy:latest"
  amd64: "f0rc3/barcodebuddy:latest"
  armhf: "f0rc3/barcodebuddy:latest"
  armv7: "f0rc3/barcodebuddy:latest"
  i386: "f0rc3/barcodebuddy:latest"
squash: false
args: {}
