name: "Barcode Buddy USB Scanner"
version: "1.1.8"
slug: "barcodebuddy-usb"
description: "Barcode Buddy with USB scanner support and Grocy ingress integration"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
init: false

# USB-Ger채te einzeln mappen
devices:
  - "/dev/input/event0:/dev/input/event0:rwm"
  - "/dev/input/event1:/dev/input/event1:rwm"
  - "/dev/input/event2:/dev/input/event2:rwm"
  - "/dev/input/event3:/dev/input/event3:rwm"

# udev f체r USB-Erkennung
udev: true

# Umgebungsvariablen setzen
environment:
  ATTACH_BARCODESCANNER: "true"

# Container Mapping
map:
  - "config:rw"
  - "ssl"

# PORT-Konfiguration
ports:
  "80/tcp": 8083

# Web UI Konfiguration
webui: "http://[HOST]:[PORT:80]"
ingress: true
ingress_port: 80
ingress_entry: "/"

# Benutzer-konfigurierbare Optionen - ERWEITERT f체r Grocy
options:
  require_api_key: false
  disable_auth: true
  debug: true
  curl_allow_insecure_ssl_ca: false
  curl_allow_insecure_ssl_host: false
  scanner_device: "/dev/input/event2"
  # NEU: Grocy-Integration (Ingress-Support)
  grocy_server_url: "http://ha.mathops.de:8123/hassio/ingress/a0d7b954_grocy"
  grocy_api_key: ""
  grocy_username: "admin"
  auto_setup_grocy: true
  use_ingress: true

# Schema f체r Validierung - ERWEITERT
schema:
  require_api_key: bool
  disable_auth: bool
  debug: bool
  curl_allow_insecure_ssl_ca: bool
  curl_allow_insecure_ssl_host: bool
  scanner_device: str
  grocy_server_url: str
  grocy_api_key: str
  grocy_username: str
  auto_setup_grocy: bool
  use_ingress: bool