name: "Barcode Buddy USB Scanner"
version: "1.1.3"
slug: "barcodebuddy-usb"
description: "Barcode Buddy with USB scanner support"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
init: false

# Privileged Modus für vollständigen Hardware-Zugriff
privileged: true

# USB-Geräte mappen (Host hat event0-event3)
devices:
  - "/dev/input:/dev/input"
  
# Zusätzliche Capabilities
cap_add:
  - SYS_RAWIO
  - DAC_OVERRIDE

# udev für USB-Erkennung
udev: true

# Umgebungsvariablen setzen
environment:
  ATTACH_BARCODESCANNER: "true"

# Container Mapping
map:
  - "config:rw"
  - "ssl"

ports:
  "80/tcp": 8083

webui: "http://[HOST]:[PORT:80]"
ingress: true
ingress_port: 0

# Benutzer-konfigurierbare Optionen
options:
  require_api_key: false
  disable_auth: true
  debug: true
  curl_allow_insecure_ssl_ca: false
  curl_allow_insecure_ssl_host: false
  scanner_device: "/dev/input/event2"

# Schema für Validierung
schema:
  require_api_key: bool
  disable_auth: bool
  debug: bool
  curl_allow_insecure_ssl_ca: bool
  curl_allow_insecure_ssl_host: bool
  scanner_device: str