# config.yaml - Einfache Lösung ohne run.sh
name: "Barcode Buddy USB Scanner"
version: "1.0.0"
slug: "barcodebuddy-usb"
description: "Barcode Buddy with USB scanner support"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
init: false

# USB-Geräte direkt weiterleiten
devices:
  - "/dev/input/event0:/dev/input/event0"
  - "/dev/input/event1:/dev/input/event1"
  - "/dev/input/event2:/dev/input/event2"

# udev für USB-Erkennung
udev: true

# Umgebungsvariablen setzen
environment:
  ATTACH_BARCODESCANNER: "true"

# Bestehende Konfiguration beibehalten
map:
  - "config:rw"
  - "ssl"

ports:
  "80/tcp": 8083

webui: "http://[HOST]:[PORT:80]"
ingress: true
ingress_port: 0

# Original Docker Image verwenden
image: "f0rc3/{arch}-barcodebuddy-homeassistant"

options:
  require_api_key: false
  disable_auth: true
  debug: false
  curl_allow_insecure_ssl_ca: false
  curl_allow_insecure_ssl_host: false

schema:
  require_api_key: bool
  disable_auth: bool
  debug: bool
  curl_allow_insecure_ssl_ca: bool
  curl_allow_insecure_ssl_host: bool
