name: "Barcode Buddy USB Scanner"
version: "1.2.3"
slug: "barcodebuddy-usb"
description: "Barcode Buddy with USB scanner support, Grocy integration (robust config)"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
init: false

# USB-Geräte einzeln mappen
devices:
  - "/dev/input/event0:/dev/input/event0:rwm"
  - "/dev/input/event1:/dev/input/event1:rwm"
  - "/dev/input/event2:/dev/input/event2:rwm"
  - "/dev/input/event3:/dev/input/event3:rwm"

# udev für USB-Erkennung
udev: true

# Umgebungsvariablen setzen
environment:
  ATTACH_BARCODESCANNER: "true"

# Container Mapping
map:
  - "config:rw"
  - "ssl"

# PORT-Konfiguration
ports:
  "80/tcp": 8083

# Web UI Konfiguration
webui: "http://[HOST]:[PORT:80]"
ingress: true
ingress_port: 80
ingress_entry: "/"

# Benutzer-konfigurierbare Optionen
options:
  # Scanner-Konfiguration
  scanner_device: "/dev/input/event3"
  debug: true
  
  # Authentication
  require_api_key: false
  disable_auth: true
  
  # SSL/TLS
  curl_allow_insecure_ssl_ca: false
  curl_allow_insecure_ssl_host: false
  
  # Grocy-Integration (KONFIGURIERBAR!)
  grocy_server_url: ""  # Leer lassen für Auto-Config
  grocy_api_key: ""     # Leer lassen für Auto-Config
  grocy_username: "admin"
  auto_setup_grocy: true
  use_ingress: true

# Schema für Validierung
schema:
  scanner_device: str
  debug: bool
  require_api_key: bool
  disable_auth: bool
  curl_allow_insecure_ssl_ca: bool
  curl_allow_insecure_ssl_host: bool
  grocy_server_url: str
  grocy_api_key: str
  grocy_username: str
  auto_setup_grocy: bool
  use_ingress: bool