name: "Barcode Buddy USB Scanner"
version: "1.1.1"
slug: "barcodebuddy-usb"
description: "Barcode Buddy with USB scanner support"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
init: false

# USB-Geräte direkt weiterleiten
devices:
  - "/dev/input/event0:/dev/input/event0"
  - "/dev/input/event1:/dev/input/event1"
  - "/dev/input/event2:/dev/input/event2"
  - "/dev/input/event3:/dev/input/event3"

# udev für USB-Erkennung
udev: true

# Umgebungsvariablen setzen
environment:
  ATTACH_BARCODESCANNER: "true"

# Container Mapping
map:
  - "config:rw"
  - "ssl"

ports:
  "80/tcp": 8083

webui: "http://[HOST]:[PORT:80]"
ingress: true
ingress_port: 0

# KEIN image: Feld - verwendet lokales Dockerfile!

# Benutzer-konfigurierbare Optionen
options:
  require_api_key: false
  disable_auth: true
  debug: false
  curl_allow_insecure_ssl_ca: false
  curl_allow_insecure_ssl_host: false
  scanner_device: "/dev/input/event3"

# Schema für Validierung
schema:
  require_api_key: bool
  disable_auth: bool
  debug: bool
  curl_allow_insecure_ssl_ca: bool
  curl_allow_insecure_ssl_host: bool
  scanner_device: str?
